#!/bin/bash

cd `dirname $0`

ee=`lsmod | grep -w fpga`
if [ -n "$ee" ]; then
	sudo rmmod fpga
fi

if [ -n "$1" ]; then
	sudo insmod fpga.ko dma_bw=$1
else
	sudo insmod fpga.ko
fi

sudo chmod 666 /dev/fpga*
